### ISSUE TITLE
検索フォームがないページで js エラーが発生する

### ISSUE THREAD

**Issue by inc2734** [kmix-39/kotonoha-tena-bbpress-enhance#2]
https://snow-monkey.2inc.org/

<img width="1147" alt="スクリーンショット 2021-01-28 10 33 29" src="https://user-images.githubusercontent.com/1094306/106077173-62f06180-6154-11eb-9b07-cf06c0567e0d.png">

**Comment by kmix-39** [comment]
…完全に不具合ですね。

bbPress かつ、検索フォームがあるページの時だけjsを読むなりの条件分岐を作るんで、ちょいお待ちを。

**Comment by inc2734** [comment]
ありがとうございます！特に急いではいないのでお手すきのときにでも。

**Comment by kmix-39** [comment]
0.2.5 で対応しました。

対応内容：
・フォーラム一覧（`bbp_is_forum_archive`）と検索（`bbp_is_search`）のみで必要ファイルを読むように

**Comment by inc2734** [comment]
ありがとうございます！普通のページではでなくなりました！
いま動作確認していたら、bbPress の検索結果ページでも同様のエラーがでていました。
https://snow-monkey.2inc.org/forums/search/?bbp_search=i&bbp_forum_id=49870&bbp_type=

**Comment by kmix-39** [comment]
あれ？検索ボックスって検索結果画面でも出てませんでしたっけ(汗) と、思っていたら「常に表示させる」オプションを有効にしたままテストしていたようです。無効時に検索結果画面ではjsを読み込まないようにしないとなので後で再度直しておきます。すみません。

> 検索結果画面に検索ボックスでるようにしたほうが良いかも？（できるなら）

これは設定に作ってありますので、必要であれば有効にされると良いかも。
キーワード未入力時の時もフォームが再度出るようになります。(あ…その辺も読み込みを直す必要有りですね……orz)

好みに合わせて設定できるって感じで作ったのは良いものの、結構パターンテストなど漏れも起きてるのでフックと設定値を共有するユーティリティクラス作ってパターンテストしやすくします…

**Comment by kmix-39** [comment]
検索結果画面に検索ボックスを出すの、「検索結果が存在しない場合」だけでしたねorz

常に表示するのをmy snow monkeyで書いていて抜けていたので、それもこちらに入れるようにします…。調整する点が幾つかあるのでちょいとお待ちをー。

**Comment by kmix-39** [comment]
0.2.7 で追加修正しました。

設定も１つ追加してあるので、再設定した方が良いかもです。
（設定値は変えてないです）

対応内容：

・検索フォームがない場合のスクリプトエラー対応
・検索結果一覧での検索フォーム表示対応（検索結果がある場合、上部に出るオプションを Snow Monkey のフックを利用して調整）
・検索結果がない場合の検索フォーム表示と検索結果がある場合の表示を切り分け（それに伴い、検索結果一覧の下部には出なくしています）
・ローカライズ文章を少し修正
・オプションに対してフックを追加（` ktpp_bbpress_enhance_get_option_$key` )

**Comment by inc2734** [comment]
良い感じっぽい気がします。ありがとうございます！
