### ISSUE TITLE
トピック一覧ページで検索フォームの表示が崩れる

### ISSUE THREAD

**Issue by inc2734** [kmix-39/kotonoha-tena-bbpress-enhance#5]
## 詳細

トピック一覧ページで検索フォームが CSS が抜けた状態で表示されます。

<img width="873" alt="スクリーンショット 2021-02-01 11 37 03" src="https://user-images.githubusercontent.com/1094306/106408518-fd68e180-6481-11eb-86c9-66be493c0d41.png">

https://snow-monkey.2inc.org/topics/

**Comment by kmix-39** [comment]
ぬぉぁ…報告ありがとうございます。
CSSはisbbpressで全体的に読む方が良さそうですかねー…

少し他にもドタバタしてるので２日中に修正します。

**Comment by kmix-39** [comment]
３点リーダー症候群のケミで…す…。
0.2.8 で、トピック一覧ページに関しての修正をしました……。

各ユーザーの検索フォームもあるので、そちらも絞り込み検索をできるように……していきたいですね…。
それらは… 0.3系で…やっていきます…………。

**Comment by inc2734** [comment]
はや！後ほど確認しますね、ありがとうございます！

**Comment by inc2734** [comment]
修正確認できました！
