### ISSUE TITLE
トピックタグのページで検索条件の部分が崩れる

### ISSUE THREAD

**Issue by inc2734** [kmix-39/kotonoha-tena-bbpress-enhance#7]
## 詳細

CSS が enqueue されていないようです。

### スクリーンショット / 図解 / 資料

<img width="892" alt="スクリーンショット 2021-03-26 14 10 15" src="https://user-images.githubusercontent.com/1094306/112585365-01d7c800-8e3d-11eb-9b00-3e1ac83b59f0.png">

https://snow-monkey.2inc.org/forums/topic-tag/event-organiser/

**Comment by kmix-39** [comment]
ぬあ……トピックタグの際の条件が抜けてますね…
全然気づかなかったです。

すみません、条件追加して対応しますので、しばしお待ちを

**Comment by inc2734** [comment]
ありがとうございます！！

**Comment by kmix-39** [comment]
0.3.0 で修正しました。

追加の対応：
なお、WP 5.7のみ対応の方向性で、Snow Monkey v14.0.2以降を必須バージョンに更新してます。
（キタジマさんの事だから常に最新だし問題ないはず）

**Comment by inc2734** [comment]
修正されていることを確認しました！ありがとうございました！
